export default {
  name: 'pageSections',
  of: [
    { type: 'accordionList' },
    { type: 'articleText' },
    { type: 'cardsDual' },
    { type: 'cardsTextGrid' },
    { type: 'cardsWideList' },
    { type: 'citiesGallery' },
    { type: 'carousel' },
    { type: 'collageDivider' },
    { type: 'heroCollage' },
    { type: 'heroLargeCard' },
    { type: 'iframePage' },
    { type: 'mapPromotion' },
    { type: 'newsPromotion' },
    { type: 'promoSponsors' },
    { type: 'promoText' },
    { type: 'sponsorsReel' },
    { type: 'statsPromotion' },
    { type: 'teamGallery' },
    { type: 'twinCardWithCollage' },
    { type: 'twinBackgroundBand' },
    { type: 'twinOverlappedCards' },
  ],
  title: 'Page Sections',
  type: 'array',
  validation: (Rule: any) =>
    Rule.required().min(1).error('"Page Content" requires at least one section.'),
};
